config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    resources :products
  end

  resources :sales do
    resources :invoices
  end

  resources :clients do
    resources :sales
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :sale
  has_many :invoice_product_joins, dependent: :destroy
  has_many :products, through: :invoice_product_joins

  accepts_nested_attributes_for :products, allow_destroy: true, reject_if: proc { |att| att['id'].blank? }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.products.build
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create

    product_models = []
    params["invoice"]["products_attributes"].each {|key, value|
      object = Product.new
      object.tipo = value["tipo"]
      object.marca = value["marca"]
      object.modelo = value["modelo"]
      object.precio = value["precio"]
      object.numero_producto = value["numero_producto"]
      product_models << object
      object.save
    }
    @invoice = Invoice.new(invoice_params)
    product_models.each do |ii|
      @invoice.products << ii
    end

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:sale_id, :fecha_despacho, :orden_transporte, :empresa, :numero_factura, products_attributes: Product.attribute_names.map(&:to_sym))
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sale_id %>
    <%= form.text_field :sale_id %>
  </div>

  <div class="field">
    <%= form.label :fecha_despacho %>
    <%= form.date_select :fecha_despacho %>
  </div>

  <div class="field">
    <%= form.label :orden_transporte %>
    <%= form.text_field :orden_transporte %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa %>
  </div>

  <div class="field">
    <%= form.label :numero_factura %>
    <%= form.number_field :numero_factura %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Tipo</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Precio</th>
        <th>Número de Producto</th>
      </tr>
    </thead>
    <tbody class='fields'>
      <%= form.fields_for :products do |f| %>
        <%= render 'product_fields', f: f%>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to_add_fields('Add Task', form, :products) %>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_product_fields.html.erb
<tr>
  <td><%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %></td>
  <td><%= f.text_field :tipo, label: false %></td>
  <td><%= f.text_field :marca, label: false %></td>
  <td><%= f.text_field :modelo, label: false %></td>
  <td><%= f.text_field :precio, label: false %></td>
  <td><%= f.text_field :numero_producto, label: false %></td>
</tr>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>
      <th>Fecha despacho</th>
      <th>Orden transporte</th>
      <th>Empresa</th>
      <th>Numero factura</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.sale %></td>
        <td><%= invoice.fecha_despacho %></td>
        <td><%= invoice.orden_transporte %></td>
        <td><%= invoice.empresa %></td>
        <td><%= invoice.numero_factura %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale:</strong>
  <%= @invoice.sale %>
</p>

<p>
  <strong>Fecha despacho:</strong>
  <%= @invoice.fecha_despacho %>
</p>

<p>
  <strong>Orden transporte:</strong>
  <%= @invoice.orden_transporte %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @invoice.empresa %>
</p>

<p>
  <strong>Numero factura:</strong>
  <%= @invoice.numero_factura %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>