config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    resources :products
  end

  resources :sales do
    resources :invoices
  end

  resources :clients do
    resources :sales
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  has_many :invoices, dependent: :destroy

  accepts_nested_attributes_for :invoices, :client, allow_destroy: true, reject_if: proc { |att| att['id'].blank? }
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @sale.invoices.build
    #@sale.client.build
    @client = @sale.build_client
    @invoice = Invoice.new
    @invoice.products.build
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @client = Client.create(rut: params["sale"]["clients"]["rut"],
                            unidad_compra: params["sale"]["clients"]["unidad_compra"],
                            razon: params["sale"]["clients"]["razon"],
                            direccion: params["sale"]["clients"]["direccion"],
                            comuna: params["sale"]["clients"]["comuna"],
                            region: params["sale"]["clients"]["region"],
                            institucion: params["sale"]["clients"]["institucion"])
    sale_params["client_id"] = @client.id
    byebug
    @invoice = Invoice.create(fecha_despacho: params["sale"]["invoices_attributes"]["fecha_despacho"],
                           orden_transporte: params["sale"]["invoices_attributes"]["orden_transporte"],
                           empresa: params["sale"]["invoices_attributes"]["empresa"],
                           numero_factura: params["sale"]["invoices_attributes"]["numero_factura"],
                           products_attributes: Product.attribute_names.map(&:to_sym))
    params["sale"]["invoices_attributes"]["sale_id"] = @sale.id
    product_models.each do |ii|
      @invoice.products << ii
    end

    @sale = Sale.new(sale_params)


    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client_id, :codigo_oc, :numero_licitacion, :fecha_envio, :estado, :moneda, :total, :forma_pago, clients_attributes: Client.attribute_names.map(&:to_sym),invoices_attributes: Invoice.attribute_names.map(&:to_sym))
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_client_fields.html.erb
<div class="row">
  <div class="col-3">
    <div class="form-group">
      <label for="rut">RUT</label>
      <input type="rut" class="form-control">
    </div>
  </div>

  <div class="col-3">
    <div class="form-group">
      <label for="unidad_compra"> Unidad de Compra</label>
      <input type="unidad_compra" class="form-control">
    </div>
  </div>

  <div class="col-sm-3">
    <div class="field">
      <label for="razon"> Razón</label>
      <input type="text" class="form-control">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3">
    <div class="form-group">
      <label for="direccion">Dirección</label>
      <input type="direccion" class="form-control">
    </div>
  </div>

  <div class="col-3">
    <div class="form-group">
      <label for="comuna"> Comuna</label>
      <input type="comuna" class="form-control">
    </div>
  </div>

  <div class="col-sm-3">
    <div class="field">
      <label for="region"> Región</label>
      <input type="region" class="form-control">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3">
    <div class="form-group">
      <label for="institucion">Institución</label>
      <input type="text" class="form-control">
    </div>
  </div>
</div>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-3">
      <div class="form-group">
        <div class="form-group">
          <label for="codigo_oc"> Código OC</label>
          <input type="codigo_oc" class="form-control">
        </div>
      </div>
    </div>

    <div class="col-3">
      <div class="field">
        <label for="numero_licitacion"> Numero de Licitacion</label>
        <input type="number" class="form-control">
      </div>
    </div>

    <div class="col-sm-3">
      <div class="field">
        <label for="fecha_envio"> Fecha de Envio</label>
        <input type="date" class="form-control">
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-3">
      <label for="estado">Estado</label>
      <select class="form-control" id="estado">
        <option>Pagada</option>
        <option>Pendiente</option>
        <option>Deuda</option>
      </select>
    </div>

    <div class="col-2">
      <label for="moneda">Moneda</label>
      <select class="form-control" id="moneda">
        <option>CLP</option>
        <option>UF</option>
        <option>US</option>
      </select>
    </div>

    <div class="col-2">
      <div class="field">
        <label for="total"> Total </label>
        <input type="number" class="form-control">
      </div>
    </div>

    <div class="col-2">
      <label for="forma_pago">Forma de Pago</label>
      <select class="form-control" id="forma_pago">
        <option>A 30 dias</option>
        <option>Más de 30 dias</option>
      </select>
    </div>
  </div>

  <div class="row">


    <div class="col-3">
      <label for="client_id">ID Cliente</label>
      <input type="client_id" class="form-control">
    </div>

  </div>


  <%= f.fields_for :clients do |client| %>
    <% render 'client_fields', form: client %>
  <% end %>

  <%= f.fields_for :invoices do |invoice| %>
    <% render 'invoice_fields', form: invoice %>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/_invoice_fields.html.erb
<div class="row">
  <div class="col-3">
    <div class="form-group">
      <label for="sale_id">sale</label>
      <input type="sale_id" class="form-control">
    </div>
  </div>

  <div class="col-3">
    <div class="form-group">
      <label for="fecha_despacho"> Fecha de Despacho</label>
      <input type="date" class="form-control">
    </div>
  </div>

  <div class="col-sm-3">
    <div class="field">
      <label for="orden_transporte"> Orden de Transporte</label>
      <input type="text" class="form-control">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3">
    <div class="form-group">
      <label for="empresa">empresa</label>
      <input type="text" class="form-control">
    </div>
  </div>

  <div class="col-3">
    <div class="form-group">
      <label for="numero_factura"> Numero de Factura</label>
      <input type="number" class="form-control">
    </div>
  </div>

</div>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Tipo</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Precio</th>
        <th>Número de Producto</th>
      </tr>
    </thead>
    <tbody class='fields'>
      <%= form.fields_for :products do |f| %>
        <%= render 'product_fields', f: f%>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to_add_fields('Add Task', form, :products) %>
  </div>

app/views/sales/_product_fields.html.erb
<tbody>
<tr>
  <td>
    <%# <%= f.input_field :_destroy, as: :hidden %> %>
    <%= link_to 'Delete', '#', class: 'remove_record' %>
  </td>
  <td><%= f.text_field :tipo, label: false %></td>
  <td><%= f.text_field :marca, label: false %></td>
  <td><%= f.text_field :modelo, label: false %></td>
  <td><%= f.text_field :precio, label: false %></td>
  <td><%= f.text_field :numero_producto, label: false %></td>
</tr>
</tbody>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Codigo oc</th>
      <th>Numero licitacion</th>
      <th>Fecha envio</th>
      <th>Estado</th>
      <th>Moneda</th>
      <th>Total</th>
      <th>Forma pago</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.client %></td>
        <td><%= sale.codigo_oc %></td>
        <td><%= sale.numero_licitacion %></td>
        <td><%= sale.fecha_envio %></td>
        <td><%= sale.estado %></td>
        <td><%= sale.moneda %></td>
        <td><%= sale.total %></td>
        <td><%= sale.forma_pago %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h2>Nueva Venta</h2>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @sale.client %>
</p>

<p>
  <strong>Codigo oc:</strong>
  <%= @sale.codigo_oc %>
</p>

<p>
  <strong>Numero licitacion:</strong>
  <%= @sale.numero_licitacion %>
</p>

<p>
  <strong>Fecha envio:</strong>
  <%= @sale.fecha_envio %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @sale.estado %>
</p>

<p>
  <strong>Moneda:</strong>
  <%= @sale.moneda %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total %>
</p>

<p>
  <strong>Forma pago:</strong>
  <%= @sale.forma_pago %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>